Remove 'setcachsize' from zoneinfo __all__ list
This function was removed from the zoneinfo module in version 2.3 and
causes an error when doing a wildcard import from the zoneinfo module.

>>> from dateutil.zoneinfo import *
Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      AttributeError: 'module' object has no attribute 'setcachesize'